name: main
on:
  push:
    branches:
      - main

jobs:
  sync_jobs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'
      - name: running requirements
        working-directory: .
        run: pip install -r requirements.txt
      - name: Check if data directory and file exist
        run: ls -la data
      - name: Update the project
        env:
          HOSTNAME: ${{ secrets.HOSTNAME }}
          PORT: ${{ secrets.PORT }}
          DATABASE: ${{ secrets.DATABASE }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        working-directory: src
        run: python main.py